---
- name: Create repo servers
  hosts: repo-server
  remote_user: tony
  become: yes

  roles:
    - aptly-repo
    - aptly-nginx

  vars_prompt:
    - name: "aptly_gpg_passphrase"
      prompt: "Enter GPG passphrase (possibly insecure)"
      private: yes
