-
    name: Create aptly user
    # TODO put in common role
    user: name={{ aptly_user }} shell=/bin/bash
    become: yes
-
    name: Install nginx
    apt: name={{ item }} state=present update_cache=yes
    with_items:
        - nginx
    become: yes
-
    name: Remove nginx 'it works' page
    file: path=/etc/nginx/sites-enabled/default state=absent
    become: yes
-
    name: Upload nginx configuration file
    template: src=nginx-aptly.conf.j2 dest=/etc/nginx/sites-available/aptly.conf owner=root group=root mode=644
    notify: restart nginx
    become: yes
-
    name: Create nginx configuration symlinks
    file: src=/etc/nginx/sites-available/aptly.conf dest=/etc/nginx/sites-enabled/aptly.conf state=link
    notify: restart nginx
    become: yes
